default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: get_those_tweets_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: get_those_tweets_test
  pool: 5
  username: 
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: get_those_tweets_prod
