development:
  adapter: postgresql
  encoding: unicode
  database: HEROKU_POSTGRESQL_NAVY_URL
  pool: 5
  username: henry
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: HEROKU_POSTGRESQL_NAVY_URL
  pool: 5
  username: henry
  password:

production:
  <<: *default
  database: HEROKU_POSTGRESQL_NAVY_URL
