# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0fed95d59afeb4633dd2c7c75e0d2182b819cdce60864dba3027b501c74612accf01d4a2c3ae96d5b90f44e03ef4c0bd2909fbf3766c1162f68d49cfca62f8

test:
  secret_key_base: 6f1497ce0ccf1d0fcbb15e44d35d1a8d32e267ae402bb8ca00567f15644665997518bd3a26a1c9aee8f1a28ad025d4765f7599688fa7f6678d037b9ab001f0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
